---
# This is required, to map the project name to the actual
# object-group network name that needs to be configured
projects:
  - demo-zone: object-group-network-name1
  - frontend: object-group-network-name2
  - monitors: object-group-network-name3
# This is required, to restrict what networks are allowed
# to be added/removed from the specified object-groups.
networks:
  - '10.10.10.0/24'
  - '192.168.11.128/25'
  - '172.17.18.32/27'
